#!/bin/bash
#   Copyright (C) 2013-2015 Computer Sciences Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


### BEGIN INIT INFO
# Provides:          EzSecurity-Async
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: This is EzSecurity with Asynchronous support
# Description:       This is EzSecurity
#                    This starts up the EzSecurity service
### END INIT INFO

# Source function library.
. /etc/init.d/functions

EZ_PREFIX="/opt/ezbake/ezbake-security-service"
PORT=30100
APP_NAME=system_services
THRIFT_TRANSPORT_OPT="-D tframe.transport=true"

if [ -f "${EZ_PREFIX}/bin/ezsecurity-env.sh" ]; then
    . "${EZ_PREFIX}/bin/ezsecurity-env.sh"
fi

if [ -f "${EZ_PREFIX}/bin/ezsecurity-env-override.sh" ]; then
    . "${EZ_PREFIX}/bin/ezsecurity-env-override.sh"
fi

SERVICE_NAME=${SERVICE_NAME:-EzBakeSecurityService}

servicename=EzSecurityAsync
RETVAL=0
LOCKFILE=/var/lock/subsys/${servicename}
PIDFILE="${EZ_PREFIX}/${servicename}.pid"

ASYNC_OPTS="-a system_services ${THRIFT_TRANSPORT_OPT}"
JAVA_OPTS="-jar ${THRIFT_RUNNER_JAR} ${THRIFT_RUNNER_OPTS} ${ADDITIONAL_THRIFT_RUNNER_OPTS} ${ASYNC_OPTS}"

start() {
    echo -n "Starting ${servicename} (framed transports): "

    daemon --user $EZ_USER --pidfile ${PIDFILE} "cd \"${EZ_PREFIX}\" && { ${STETHOSCOPE} & java ${JAVA_OPTS} ; } &>/dev/null & echo \$! > ${PIDFILE}"
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
    echo
    start_logstash
    return $RETVAL
}

stop() {
    echo -n "Shutting down ${servicename} (framed transports): "
    PID=$(<${PIDFILE})
    PGID=`ps -ejHf | awk -v p=$PID '($2==p){print $4}'`
    kill -TERM -${PGID}
    RETVAL=$?
    rm -f $PIDFILE
    rm -f $LOCKFILE
    echo
    stop_logstash
    return $RETVAL
}

LOGSTASH_HELPER=/opt/ezbake/ezbake-logstash-helper/logstash.sh
function start_logstash() {
    if [ -f "${LOGSTASH_HELPER}" ]; then
	runuser ${EZ_USER} <<-END
	source "${LOGSTASH_HELPER}"
	start_logstash "${SERVICE_NAME}" "${SERVICE_NAME}-ASYNC" "${EZ_PREFIX}/logstash/async" "${EZBAKE_LOG_DIR}/system_services/system_services_EzBakeSecurityService"
	END
    fi
}

function stop_logstash() {
    if [ -f "${LOGSTASH_HELPER}" ]; then
	runuser ${EZ_USER} <<-END
	source "${LOGSTASH_HELPER}"
	stop_logstash "${APP_NAME}" "${SERVICE_NAME}" "${EZ_PREFIX}/logstash/async"
	END
    fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
    echo -n "Status of ${servicename} (framed transports): "
    PID=`cat "$PIDFILE"`
    if [ -f "$PIDFILE" -a -d "/proc/${PID}" ]; then
        echo -n "running"
        RETVAL=0
    elif [ -f "$LOCKFILE" ]; then
        echo -n "dead"
        RETVAL=2
    else
        echo -n "dead"
        RETVAL=3
    fi
    echo
    ;;
    restart)
    stop
	start
	;;
    *)
	echo "Usage: ${servicename} {start|stop|status|restart}"
	exit 1
	;;
esac
exit $RETVAL


