#!/bin/bash
#   Copyright (C) 2013-2014 Computer Sciences Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

BIN_DIR=$(cd $(dirname $0); pwd)
export EZCONFIGURATION_DIR=${EZCONFIGURATION_DIR:=/etc/sysconfig/ezbake}
export EZDEPLOYER_SERVICE_NAME=${EZDEPLOYER_SERVICE_NAME:=ezdeployer}

source ~/.bash_profile

java -jar $BIN_DIR/thrift-runner.jar "$@" -j $BIN_DIR/ezdeployer.jar -s "$EZDEPLOYER_SERVICE_NAME" --host_name $HOSTNAME -p 30000:34999 -D ezbake.security.ssl.dir=/opt/ezdeployer/etc/ezbake/pki -P /opt/ezdeployer/etc -D ezbake.security.app.id=04 -D openshift.timeout=600000 -D ezbake.shared.secret.environment.variable="EZBAKE_ENCRYPTION_SECRET" -c ezbake.deployer.EzBakeDeployerHandler