# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.forward_agent = true

  config.vm.box = "centos65"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"

   config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "1536"]
   end

  config.vm.provision :shell, inline: "
    yum install -y \
      java-1.7.0-openjdk-devel \
      readline-devel \
      zlib-devel \
      openssl-devel \
      bzip2-devel \
      ruby-devel rubygems
    gem install fpm
    useradd ezca
  "

  config.vm.synced_folder "~/.pip", "/home/vagrant/.pip"
  config.vm.provision "file", source: "~/.pypirc", destination: ".pypirc"
  config.vm.provision :shell, :path => '.provision/shell/pyenv.sh'
  config.vm.synced_folder "~/.m2", "/home/vagrant/.m2"
  config.vm.provision :shell, path: ".provision/shell/maven.sh"
end
